Add Condition Profile
NIH-NCPI/ncpi-fhir-ig-2 pull request #32
Opened 2024-08-12 16:03 UTC by aw3334

# Motivation

This adds the condition profile to the main branch. Logical models, code systems, value sets and examples are also included.

# Approach

Created FSH code to define above #14

2024-08-13 20:31 UTC, a-l-holmes requested changes

2024-08-22 20:56 UTC, aw3334 commented on README.md
> -Welcome to NCPI FHIR IG 2. The goal for this repository is to relaunch the IG project
Not sure how this got changed - definitely accidental. Resolved in commit [6b486c8](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/32/commits/6b486c80cef3282a9ce487c7e4a302d3587cee87)

2024-08-22 20:57 UTC, aw3334 commented on input/fsh/examples/participant.fsh
Also accidental

2024-08-23 14:30 UTC, aw3334 commented on fsh-generated/resources/StructureDefinition-ncpi-condiiton.json
fixed type in commit [ec5ee15](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/32/commits/ec5ee151081a0950158cd56ce09c6a0c57fe7547)

2024-08-27 14:09 UTC, aw3334 commented on input/fsh/examples/condition.fsh
> +Instance: condition-example
fixed in [120d1c9](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/32/commits/120d1c99ce5402c2ef2a875e89f63f2cc1cf0844)

2024-08-27 14:09 UTC, aw3334 commented on input/fsh/examples/condition.fsh
> +* subject = Reference(PT-KZG2CZ95)
fixed in. [120d1c9](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/32/commits/120d1c99ce5402c2ef2a875e89f63f2cc1cf0844)

2024-08-28 17:27 UTC, aw3334 commented on fsh-generated/resources/StructureDefinition-ncpi-condiiton.json
fixed in [6d8add4](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/32/commits/6d8add4f77b5bcbf1ced603fab489585d618ae08)

2024-08-28 18:09 UTC, aw3334 commented on input/fsh/modules/condition.fsh
> +* bodySite ^short = "Location information, such as site and/or laterality, of the condition. Multiple values should be interpreted cumulatively, so complex location information, such as \"right lung\
I added the 2 qualifiers in commit [f1baa87](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/32/commits/f1baa878ddf96aa95967ac8321b3f83cbfb97e66). Please let me know if I need to make any changes! @a-l-holmes

2024-08-29 19:33 UTC, aw3334 commented on input/fsh/modules/condition.fsh
> +* component ^short = "The age of onset for this condition. Could be expressed with a term, an age, or an age range."
Added slicing for component in commit [2e8188a](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/32/commits/2e8188aa66d49d1caa69e524da0f450d262951ba)

2024-09-09 12:59 UTC, a-l-holmes commented on input/fsh/modules/condition.fsh
> +* component[otherModifiers].code = #ageAtOnset
The code for this should be #otherModifiers instead of #ageAtOnset

2024-09-09 13:00 UTC, a-l-holmes commented on input/fsh/modules/condition.fsh
> +* component[stage].code = #ageAtOnset
The code here should be #stage instead of #ageAtOnset

2024-09-09 13:03 UTC, a-l-holmes requested changes
Two small slicing corrections but then we should be ready to merge 😺

2024-09-10 16:29 UTC, aw3334 reviewed
Fixed final typos in commit [2c18e63](https://github.com/NIH-NCPI/ncpi-fhir-ig-2/pull/32/commits/2c18e633bb2c30fd8749baccf203a72b4146eae1)

2024-09-10 17:59 UTC, a-l-holmes approved these changes

2024-09-10 18:53 UTC, merged